### PR TITLE
fix validators tab scroll

### LINKED ISSUE #69: Fix: tabs index behavior (validators page)
Number 2 - 
right now the index number is having counter-intuitive behavior. If one clicks on a tab and scrolls to a certain range, the other tabs go to the same scroll range automatically. It needs to be fixed to the behavior that the other tabs start from the head. 

截圖 2022-03-03 下午5 52 44

### PR DESCRIPTION
**Pull request by yayay927**
closes #69 

## Checklist
- [x] Ran Linting
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [ ] Wrote unit tests.
- [x] Added an entry to the `CHANGELOG.md` file.
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

File: src/hooks/use_react_window.ts [hunk 1]
```diff
@@ -22,11 +22,19 @@ export const useList = () => {
     };
   };
 
+  const resetToTop = () => {
+    // this reset list to the first row when click a new tab
```
Comment (ryuash) [inline src/hooks/use_react_window.ts:26]: Actually, It's just a util function. It doesn't care it there is a new tab or not.
If you want to make it informative you should go the following:
https://stackoverflow.com/questions/23072286/where-is-the-syntax-for-typescript-comments-documented

File: src/hooks/use_react_window.ts [hunk 2]
```diff
@@ -8,8 +8,8 @@ import * as R from 'ramda';
 // reusable hook helpers for react window list components
 
 export const useList = () => {
-  const listRef = useRef({});
-  const rowHeights = useRef({});
+  const listRef:any = useRef();
```
Comment (ryuash) [inline src/hooks/use_react_window.ts:11]: I'm not sure if this breaks anything but we should follow the rule, `If it's not broken. Don't fix it`.

File: src/screens/validators/components/list/components/desktop/index.tsx [hunk 3]
```diff
@@ -1,9 +1,11 @@
-import React from 'react';
+import React, { useEffect } from 'react';
```
Comment (ryuash) [inline src/screens/validators/components/list/components/desktop/index.tsx:1]: To follow our current folder structure we should make a `src/screens/validators/components/list/components/desktop/hooks.ts`

and move the `useEffect` in there

File: src/screens/validators/components/list/components/desktop/index.tsx [hunk 4]
```diff
@@ -1,9 +1,11 @@
...
 import classnames from 'classnames';
 import numeral from 'numeral';
 import useTranslation from 'next-translate/useTranslation';
 import AutoSizer from 'react-virtualized-auto-sizer';
-import { VariableSizeGrid as Grid } from 'react-window';
+import {
+  VariableSizeGrid as Grid,
+} from 'react-window';
```
Comment (ryuash) [inline src/screens/validators/components/list/components/desktop/index.tsx:8]: Is your linter fighting?

File: src/screens/validators/components/list/components/desktop/index.tsx [hunk 5]
```diff
@@ -63,6 +66,10 @@ const Desktop: React.FC<{
     });
   });
 
+  useEffect(() => {
+    resetToTop();
+  }, [props]);
+
```
Comment (ryuash) [inline src/screens/validators/components/list/components/desktop/index.tsx:72]: Not props.
You didn't pass the `tabs` prop down to this component. We want to listen to `tabs`, not `props` that's too much. Also move this inside a hook folder

File: src/screens/validators/components/list/components/mobile/index.tsx [hunk 6]
```diff
@@ -54,6 +55,10 @@ const Mobile: React.FC<{
     });
   });
 
+  useEffect(() => {
+    resetToTop();
+  }, [items]);
+
```
Comment (ryuash) [inline src/screens/validators/components/list/components/mobile/index.tsx:61]: Same comments as Desktop component

**Review by ryuash — CHANGES_REQUESTED** [review]

File: src/hooks/use_react_window.ts (hunk 2 above)
Comment (yayay927) [reply src/hooks/use_react_window.ts:11]: I fix because it was broken~

File: src/screens/validators/components/list/components/desktop/index.tsx (hunk 4 above)
Comment (yayay927) [reply src/screens/validators/components/list/components/desktop/index.tsx:8]: Very weird, I'll watch out.

File: src/screens/validators/components/list/components/desktop/index.tsx (hunk 5 above)
Comment (yayay927) [reply src/screens/validators/components/list/components/desktop/index.tsx]: Updated.

File: src/screens/validators/components/list/components/mobile/index.tsx (hunk 6 above)
Comment (yayay927) [reply src/screens/validators/components/list/components/mobile/index.tsx:60]: Updated.

File: src/screens/validators/components/list/components/desktop/index.tsx (hunk 3 above)
Comment (yayay927) [reply src/screens/validators/components/list/components/desktop/index.tsx]: Updated.

File: src/hooks/index.ts [hunk 7]
```diff
@@ -15,6 +15,7 @@ export {
   useList,
   useListRow,
   useGrid,
+  resetToTop,
```
Comment (ryuash) [inline src/hooks/index.ts:18]: Hmm..no, I think should exist in both `useGrid` and `useList` but not a standalone `resetToTop` as you can access both ref in those hooks directly. But your standalone requires a pass..
While the logic does work it's a bit out of character for the flow

**Review by ryuash — CHANGES_REQUESTED** [review]
Overall, I think i'm looking for something more on the lines of the following:

```
// index file
const {
    gridRef,
    columnRef,
    onResize,
    getColumnWidth,
    getRowHeight,
  } = useGrid(columns);
  
  useDesktop(state.tab, gridRef);
  
  // hook file
  const useDesktop = (tab: number, ref: React.RefObject<unknown>) => {
    useEffect(() => {
      if (ref.current != null) {
        ref.current.scrollToItem({
          rowIndex: 0,
        });
      }
    }, [tab]);
  }
```
I don't see a need for `scrollToTop` as it's not globally used and only for `validators` list at the moment. Let me know if this makes sense or you disagree

File: src/hooks/index.ts (hunk 7 above)
Comment (yayay927) [reply src/hooks/index.ts:18]: Updated.

**Review by ryuash — APPROVED** [review]
